// Scaffold generated by home_widget. Adjust the widget for your needs.

import SwiftUI
import WidgetKit

@main
struct FileWidgetHomeWidgetBundle: WidgetBundle {
  var body: some Widget {
    FileWidgetHomeWidget()
  }
}
