include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-raw-types: true
    strict-inference: true
    strict-casts: true

linter:
  rules:
    - public_member_api_docs
    - require_trailing_commas