// Scaffold generated by home_widget. Adjust the widget for your needs.

import WidgetKit
import SwiftUI

@main
struct ImageWidgetHomeWidgetBundle: WidgetBundle {
  var body: some Widget {
    ImageWidgetHomeWidget()
  }
}
