// Scaffold generated by home_widget. Adjust the widget for your needs.
import SwiftUI
import WidgetKit

private let appGroupId = "group.es.antonborri.exampleHomeWidget"
private let imageKey = "image"

struct Provider: TimelineProvider {
  func placeholder(in context: Context) -> ImageWidgetHomeWidgetEntry {
    ImageWidgetHomeWidgetEntry(date: Date(), imagePath: nil)
  }

  func getSnapshot(in context: Context, completion: @escaping (ImageWidgetHomeWidgetEntry) -> Void)
  {
    completion(ImageWidgetHomeWidgetEntry(date: Date(), imagePath: Self.resolvedImagePath()))
  }

  func getTimeline(in context: Context, completion: @escaping (Timeline<Entry>) -> Void) {
    let entry = ImageWidgetHomeWidgetEntry(date: Date(), imagePath: Self.resolvedImagePath())
    completion(Timeline(entries: [entry], policy: .atEnd))
  }

  private static func resolvedImagePath() -> String? {
    let prefs = UserDefaults(suiteName: appGroupId)
    guard let path = prefs?.string(forKey: imageKey), !path.isEmpty else { return nil }
    guard FileManager.default.fileExists(atPath: path) else { return nil }
    return path
  }
}

struct ImageWidgetHomeWidgetEntry: TimelineEntry {
  let date: Date
  /// Absolute path to the PNG written by home_widget; nil if missing or not on disk.
  let imagePath: String?
}

struct ImageWidgetHomeWidgetEntryView: View {
  var entry: Provider.Entry

  var body: some View {
    GeometryReader { geo in
      ZStack {
        Color.white
        if let path = entry.imagePath, let uiImage = UIImage(contentsOfFile: path) {
          Image(uiImage: uiImage)
            .resizable()
            .scaledToFit()
            .frame(width: geo.size.width, height: geo.size.height)
        } else {
          Text("Open App to save Image")
            .multilineTextAlignment(.center)
            .foregroundColor(Color.secondary)
            .frame(width: geo.size.width, height: geo.size.height, alignment: .center)
        }
      }
    }
  }
}

struct ImageWidgetHomeWidget: Widget {
  let kind: String = "ImageWidgetHomeWidget"

  var body: some WidgetConfiguration {
    StaticConfiguration(kind: kind, provider: Provider()) { entry in
      ImageWidgetHomeWidgetEntryView(entry: entry)
    }
    .configurationDisplayName("ImageWidgetHomeWidget")
  }
}
