blank_issues_enabled: false
contact_links:
  - name: I need a help with building my Widget.
    url: https://github.com/ABausG/home_widget/discussions
    about: Have a look at the discussions, maybe your question is already answered. Or the community can help you!