// Scaffold generated by home_widget. Adjust the widget for your needs.
package es.antonborri.configurable_widget

import es.antonborri.home_widget.HomeWidgetGlanceWidgetReceiver

class ConfigurableWidgetHomeWidgetReceiver :
    HomeWidgetGlanceWidgetReceiver<ConfigurableWidgetHomeWidget>() {
  override val glanceAppWidget = ConfigurableWidgetHomeWidget()
}
