// Scaffold generated by home_widget. Adjust the widget for your needs.
package es.antonborri.file_and_images

import android.content.Context
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.glance.GlanceId
import androidx.glance.GlanceModifier
import androidx.glance.appwidget.GlanceAppWidget
import androidx.glance.appwidget.provideContent
import androidx.glance.background
import androidx.glance.currentState
import androidx.glance.layout.Alignment
import androidx.glance.layout.Column
import androidx.glance.layout.fillMaxSize
import androidx.glance.layout.padding
import androidx.glance.text.Text
import androidx.glance.text.TextStyle
import es.antonborri.home_widget.HomeWidgetGlanceState
import es.antonborri.home_widget.HomeWidgetGlanceStateDefinition
import es.antonborri.home_widget.HomeWidgetPlugin
import java.io.File
import org.json.JSONObject

class FileWidgetHomeWidget : GlanceAppWidget() {
  override val stateDefinition = HomeWidgetGlanceStateDefinition()

  override suspend fun provideGlance(context: Context, id: GlanceId) {
    provideContent { WidgetContent(currentState()) }
  }

  override suspend fun providePreview(context: Context, widgetCategory: Int) {
    provideContent {
      WidgetContent(HomeWidgetGlanceState(HomeWidgetPlugin.getData(context)), preview = true)
    }
  }

  companion object {
    /** Same id as HomeWidget.saveFile in Flutter (`_fileJsonKey` in main.dart). */
    internal const val FILE_JSON_KEY = "fileJson"
    private const val DEFAULT_JSON = "{ \"name\": \"World\" }"
    private const val PREVIEW_JSON = "{ \"name\": \"Preview\" }"
  }

  @Composable
  private fun WidgetContent(currentState: HomeWidgetGlanceState, preview: Boolean = false) {
    val prefs = currentState.preferences
    val jsonPath = prefs.getString(FILE_JSON_KEY, null)
    val jsonString: String
    val name: String
    if (jsonPath != null && File(jsonPath).isFile) {
      jsonString = File(jsonPath).readText(Charsets.UTF_8)
      name =
          try {
            JSONObject(jsonString).optString("name", "World").ifEmpty { "World" }
          } catch (_: Exception) {
            "World"
          }
    } else if (preview) {
      jsonString = PREVIEW_JSON
      name = "Preview"
    } else {
      jsonString = DEFAULT_JSON
      name = "World"
    }

    Column(
        modifier = GlanceModifier.fillMaxSize().background(Color.White).padding(16.dp),
        verticalAlignment = Alignment.Vertical.Top,
        horizontalAlignment = Alignment.Horizontal.Start,
    ) {
      Text(text = "Hello $name!")
      Text(text = jsonString, style = TextStyle(fontSize = 11.sp))
    }
  }
}
