// Scaffold generated by home_widget. Adjust the widget for your needs.
package es.antonborri.file_and_images

import android.content.Context
import androidx.core.os.ConfigurationCompat
import es.antonborri.home_widget.HomeWidgetGlanceWidgetReceiver
import es.antonborri.home_widget.HomeWidgetPlugin
import java.io.File

class FileWidgetHomeWidgetReceiver : HomeWidgetGlanceWidgetReceiver<FileWidgetHomeWidget>() {
  override val glanceAppWidget = FileWidgetHomeWidget()

  override fun previewFingerprint(context: Context): String {
    val jsonPath =
        HomeWidgetPlugin.getData(context).getString(FileWidgetHomeWidget.FILE_JSON_KEY, "") ?: ""
    val file = File(jsonPath)
    return listOf(
            jsonPath,
            // The path stays the same while the file is rewritten, so its content changes with it.
            if (file.isFile) file.lastModified().toString() else "",
            ConfigurationCompat.getLocales(context.resources.configuration).toLanguageTags(),
        )
        .joinToString("|")
  }
}
