// Scaffold generated by home_widget. Adjust the widget for your needs.
package es.antonborri.file_and_images

import es.antonborri.home_widget.HomeWidgetGlanceWidgetReceiver

class ImageWidgetHomeWidgetReceiver : HomeWidgetGlanceWidgetReceiver<ImageWidgetHomeWidget>() {
  override val glanceAppWidget = ImageWidgetHomeWidget()
}
