// Scaffold generated by home_widget. Adjust the widget for your needs.

package es.antonborri.file_and_images

import android.content.Context
import android.graphics.BitmapFactory
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import androidx.glance.GlanceId
import androidx.glance.GlanceModifier
import androidx.glance.Image
import androidx.glance.appwidget.GlanceAppWidget
import androidx.glance.appwidget.provideContent
import androidx.glance.background
import androidx.glance.currentState
import androidx.glance.layout.Alignment
import androidx.glance.layout.Box
import androidx.glance.layout.ContentScale
import androidx.glance.layout.fillMaxSize
import androidx.glance.layout.padding
import androidx.glance.text.Text
import es.antonborri.home_widget.HomeWidgetGlanceState
import es.antonborri.home_widget.HomeWidgetGlanceStateDefinition
import java.io.File

class ImageWidgetHomeWidget : GlanceAppWidget() {
  override val stateDefinition = HomeWidgetGlanceStateDefinition()

  override suspend fun provideGlance(context: Context, id: GlanceId) {
    provideContent { WidgetContent(currentState()) }
  }

  companion object {
    /** Same id as HomeWidget.saveImage / saveWidgetData in Flutter (`_imageKey` in main.dart). */
    private const val IMAGE_KEY = "image"
  }

  @Composable
  private fun WidgetContent(currentState: HomeWidgetGlanceState) {
    val prefs = currentState.preferences
    val imagePath = prefs.getString(IMAGE_KEY, null)
    val bitmap =
        imagePath?.takeIf { File(it).isFile }?.let { path -> BitmapFactory.decodeFile(path) }

    Box(
        modifier = GlanceModifier.fillMaxSize().background(Color.White),
        contentAlignment = Alignment.Center,
    ) {
      Box(
          modifier = GlanceModifier.fillMaxSize().padding(16.dp),
          contentAlignment = Alignment.Center,
      ) {
        if (bitmap != null) {
          Image(
              provider = androidx.glance.ImageProvider(bitmap),
              contentDescription = null,
              modifier = GlanceModifier.fillMaxSize(),
              contentScale = ContentScale.Fit,
          )
        } else {
          Text(text = "Open App to save Image")
        }
      }
    }
  }
}
