import 'dart:io';

import 'package:path/path.dart' as p;

import '../util/android_package.dart';
import '../util/android_templates.dart';
import '../util/android_wiring.dart';
import '../util/logger.dart';
import '../util/fs.dart';
import '../util/naming.dart';

/// Scaffolds a placeholder Android Glance widget and wires it into the
/// project.
final class AndroidWidgetScaffold {
  /// Creates a new [AndroidWidgetScaffold].
  AndroidWidgetScaffold({
    required this.projectRoot,
    required this.widgetClassName,
  });

  /// The root directory of the Flutter project.
  final Directory projectRoot;

  /// The Kotlin class name for the generated widget.
  final String widgetClassName;

  /// Create Android placeholders using Jetpack Compose (Glance) and wire them
  /// into Gradle/AndroidManifest in an idempotent way.
  Future<void> run() async {
    final androidAppDir = Directory(p.join(projectRoot.path, 'android', 'app'));
    if (!androidAppDir.existsSync()) {
      logger.warn(
        'Warning: android/app/ not found. Skipping Android scaffolding.',
      );
      return;
    }

    final packageName = tryDetectAndroidPackage(projectRoot) ?? 'com.example';
    final packagePath = packageName.split('.').join(p.separator);

    final kotlinDir = Directory(
      p.join(
        projectRoot.path,
        'android',
        'app',
        'src',
        'main',
        'kotlin',
        packagePath,
      ),
    );

    final resXmlDir = Directory(
      p.join(projectRoot.path, 'android', 'app', 'src', 'main', 'res', 'xml'),
    );

    final widgetFile = File(p.join(kotlinDir.path, '$widgetClassName.kt'));
    final receiverFile = File(
      p.join(kotlinDir.path, '${widgetClassName}Receiver.kt'),
    );

    // `@xml/<name>` used in AndroidManifest receiver meta-data.
    final providerInfoName = toSnakeCase(widgetClassName);
    final providerInfoFile = File(
      p.join(resXmlDir.path, '$providerInfoName.xml'),
    );

    await ensureDir(kotlinDir);
    await ensureDir(resXmlDir);

    const header =
        '// Scaffold generated by home_widget. Adjust the widget for your needs.';

    await writeFileIfMissing(
      widgetFile,
      androidGlanceWidgetTemplate(
        packageName: packageName,
        widgetClassName: widgetClassName,
        header: header,
      ),
    );

    await writeFileIfMissing(
      receiverFile,
      androidGlanceReceiverTemplate(
        packageName: packageName,
        widgetClassName: widgetClassName,
        header: header,
      ),
    );

    await writeFileIfMissing(
      providerInfoFile,
      androidAppWidgetProviderInfoTemplate(
        initialLayoutName: 'glance_default_loading_layout',
        header: '<!-- $header -->',
      ),
    );

    // Best-effort: wire up Gradle + AndroidManifest.xml.
    await ensureAndroidGlanceGradleSetup(projectRoot);
    await ensureAndroidManifestReceiver(
      projectRoot,
      widgetClassName: widgetClassName,
      appPackageName: packageName,
      providerInfoName: providerInfoName,
    );
  }
}
