import 'dart:io';

import 'package:path/path.dart' as p;

import '../util/logger.dart';
import '../util/entitlements.dart';
import '../util/fs.dart';
import '../util/ios_templates.dart';
import '../util/xcode_pbxproj_patcher.dart';

/// Scaffolds a placeholder iOS WidgetKit extension and wires it into the
/// Xcode project.
final class IosWidgetScaffold {
  /// Creates a new [IosWidgetScaffold].
  IosWidgetScaffold({required this.projectRoot, required this.widgetClassName});

  /// The root directory of the Flutter project.
  final Directory projectRoot;

  /// The Swift class name for the generated widget extension.
  final String widgetClassName;

  /// Create iOS widget-extension placeholders.
  Future<void> run({required String appGroupId}) async {
    final iosDir = Directory(p.join(projectRoot.path, 'ios'));
    if (!iosDir.existsSync()) {
      logger.warn('Warning: ios/ not found. Skipping iOS scaffolding.');
      return;
    }

    final xcodeproj = File(
      p.join(iosDir.path, 'Runner.xcodeproj', 'project.pbxproj'),
    );
    if (!xcodeproj.existsSync()) {
      logger.warn(
        'Warning: ios/Runner.xcodeproj/project.pbxproj not found. '
        'Skipping iOS Widget Extension target wiring.',
      );
    }

    // Create the Widget Extension folder and files.
    final extensionDir = Directory(p.join(iosDir.path, widgetClassName));
    await ensureDir(extensionDir);

    final widgetSwift = File(p.join(extensionDir.path, 'Widget.swift'));
    final widgetBundleSwift = File(
      p.join(extensionDir.path, 'WidgetBundle.swift'),
    );
    final infoPlist = File(p.join(extensionDir.path, 'Info.plist'));
    final extensionEntitlements = File(
      p.join(iosDir.path, '$widgetClassName.entitlements'),
    );

    const header =
        '// Scaffold generated by home_widget. Adjust the widget for your needs.';

    await writeFileIfMissing(
      widgetSwift,
      iosWidgetSwiftTemplate(
        widgetClassName: widgetClassName,
        appGroupId: appGroupId,
        header: header,
        entryViewBody: '''
    Text("$widgetClassName (placeholder)")
    .applyContainerBackground()
''',
      ),
    );
    await writeFileIfMissing(
      widgetBundleSwift,
      iosWidgetBundleSwiftTemplate(
        widgetClassName: widgetClassName,
        header: header,
      ),
    );
    await writeFileIfMissing(
      infoPlist,
      iosInfoPlistTemplate(),
    );

    // Ensure App Group entitlement is present for the extension and Runner.
    await ensureAppGroupEntitlement(
      entitlementsFile: extensionEntitlements,
      appGroupId: appGroupId.trim().isEmpty ? 'YOUR_APP_GROUP_ID' : appGroupId,
    );

    final runnerEntitlements = File(
      p.join(iosDir.path, 'Runner', 'Runner.entitlements'),
    );
    // Flutter templates usually have this file; if not, we still create it.
    await ensureAppGroupEntitlement(
      entitlementsFile: runnerEntitlements,
      appGroupId: appGroupId.trim().isEmpty ? 'YOUR_APP_GROUP_ID' : appGroupId,
    );

    // Patch the Xcode project so the extension can actually be built.
    if (xcodeproj.existsSync()) {
      await ensureWidgetExtensionTargetInXcodeProject(
        pbxprojFile: xcodeproj,
        widgetClassName: widgetClassName,
      );

      // Ensure Runner is signed with Runner/Runner.entitlements (App Groups apply).
      await ensureRunnerEntitlementsInXcodeProject(pbxprojFile: xcodeproj);

      // Ensure Runner's deployment target is at least 14.0 (required by home_widget).
      await ensureMinimumDeploymentTargetInXcodeProject(pbxprojFile: xcodeproj);
    }
  }
}
