import 'dart:io';

import 'package:path/path.dart' as p;

import '../util/logger.dart';
import '../util/entitlements.dart';
import '../util/fs.dart';
import '../util/ios_templates.dart';
import '../util/xcode_pbxproj_patcher.dart';
import '../util/xcode_project.dart';

/// Scaffolds a placeholder iOS WidgetKit extension and wires it into the
/// Xcode project.
final class IosWidgetScaffold {
  /// Creates a new [IosWidgetScaffold].
  IosWidgetScaffold({required this.projectRoot, required this.widgetClassName});

  /// The root directory of the Flutter project.
  final Directory projectRoot;

  /// The Swift class name for the generated widget extension.
  final String widgetClassName;

  Directory get _iosDir => Directory(p.join(projectRoot.path, 'ios'));

  /// Throws a [GeneratorError] when the Xcode project cannot take the
  /// extension, or when `ios/` holds no Xcode project, so that a caller can
  /// fail before anything is written.
  Future<void> check() async {
    if (!_iosDir.existsSync()) return;
    await checkWidgetExtensionTargetInXcodeProject(
      pbxprojFile: findXcodeProject(_iosDir),
      widgetClassName: widgetClassName,
    );
  }

  /// Create iOS widget-extension placeholders.
  ///
  /// Does not [check] the Xcode project first.
  Future<void> run({required String appGroupId}) async {
    final iosDir = _iosDir;
    if (!iosDir.existsSync()) {
      logger.warn('Warning: ios/ not found. Skipping iOS scaffolding.');
      return;
    }

    final xcodeproj = findXcodeProject(iosDir);
    final runnerEntitlementsPath = defaultRunnerEntitlementsPath(
      await readXcodeProject(xcodeproj),
      projectDir: iosDir,
      projectName: xcodeProjectName(xcodeproj),
    );

    // Create the Widget Extension folder and files.
    final extensionDir = Directory(p.join(iosDir.path, widgetClassName));
    await ensureDir(extensionDir);

    final widgetSwift = File(p.join(extensionDir.path, 'Widget.swift'));
    final widgetBundleSwift = File(
      p.join(extensionDir.path, 'WidgetBundle.swift'),
    );
    final infoPlist = File(p.join(extensionDir.path, 'Info.plist'));
    final extensionEntitlements = File(
      p.join(iosDir.path, '$widgetClassName.entitlements'),
    );

    const header =
        '// Scaffold generated by home_widget. Adjust the widget for your needs.';

    await writeFileIfMissing(
      widgetSwift,
      iosWidgetSwiftTemplate(
        widgetClassName: widgetClassName,
        appGroupId: appGroupId,
        header: header,
        entryViewBody: '''
    Text("$widgetClassName (placeholder)")
    .applyContainerBackground()
''',
      ),
    );
    await writeFileIfMissing(
      widgetBundleSwift,
      iosWidgetBundleSwiftTemplate(
        widgetClassName: widgetClassName,
        header: header,
      ),
    );
    await writeFileIfMissing(
      infoPlist,
      iosInfoPlistTemplate(),
    );

    // Ensure App Group entitlement is present for the extension and Runner.
    await ensureAppGroupEntitlement(
      entitlementsFile: extensionEntitlements,
      appGroupId: appGroupId.trim().isEmpty ? 'YOUR_APP_GROUP_ID' : appGroupId,
    );

    final runnerEntitlements = File(
      p.join(iosDir.path, runnerEntitlementsPath),
    );
    // Flutter templates usually have this file; if not, we still create it.
    await ensureAppGroupEntitlement(
      entitlementsFile: runnerEntitlements,
      appGroupId: appGroupId.trim().isEmpty ? 'YOUR_APP_GROUP_ID' : appGroupId,
    );

    // Patch the Xcode project so the extension can actually be built.
    await ensureWidgetExtensionTargetInXcodeProject(
      pbxprojFile: xcodeproj,
      widgetClassName: widgetClassName,
    );

    // Ensure Runner's deployment target is at least 14.0 (required by home_widget).
    await ensureMinimumDeploymentTargetInXcodeProject(pbxprojFile: xcodeproj);
  }
}
