name: home_widget_generator
description: Annotations and DSL widgets for generating home_widget native code.
version: 0.0.1
repository: https://github.com/ABausG/home_widget

environment:
  sdk: '>=3.5.0 <4.0.0'
resolution: workspace

dev_dependencies:
  coverage: ^1.15.0
  lints: ^5.1.1
  test: ^1.25.8
  path: ^1.9.0
dependencies:
  analyzer: ^8.4.1
