name: home_widget_generator
description: Annotations and DSL widgets to generate native HomeScreen widget code for the home_widget Flutter plugin.
version: 0.0.1
repository: https://github.com/ABausG/home_widget
issue_tracker: https://github.com/ABausG/home_widget/issues
documentation: https://docs.page/ABausG/home_widget/generator
funding:
  - https://github.com/sponsors/ABausG/
topics:
  - home-screen-widget
  - code-generation
  - android
  - ios
  - home-widget

environment:
  sdk: '>=3.5.0 <4.0.0'
resolution: workspace

dev_dependencies:
  coverage: ^1.15.0
  lints: ^5.1.1
  test: ^1.25.8
  path: ^1.9.0
dependencies:
  analyzer: ^8.4.1
  home_widget: ^0.9.2
