name: Build Flutter Beta

on:
  push:
    branches:
      - flutter-beta
  pull_request:
    branches:
      - flutter-beta

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality:
    name: Quality Checks
    runs-on: macos-14
    defaults:
      run:
        working-directory: packages/home_widget

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1
        with:
          channel: beta
      - uses: bluefireteam/melos-action@v3
      - name: Analyze
        run: melos analyze
      - name: Install Formatters
        run: brew install swift-format ktfmt
      - name: Format
        run: melos format:all
      - name: Publishability
        run: flutter pub publish --dry-run
      - name: Test
        run: flutter test --coverage
      - name: Archieve Golden Failures
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: Golden failures
          retention-days: 2
          path: |
            **/test/**/failures/**/*.*
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          path: ./packages/home_widget/coverage/lcov.info

  android:
    name: Android Integration Tests
    needs: quality
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/home_widget/example

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: beta
      - uses: bluefireteam/melos-action@v3
      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Run Android Integration Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: flutter test integration_test/android_test.dart -d emulator-5554

  # iOS Test based on https://medium.com/flutter-community/run-flutter-driver-tests-on-github-actions-13c639c7e4ab
  # by @kate_sheremet
  ios:
    name: iOS Integration Tests
    needs: quality
    strategy:
      matrix:
        device:
          - "iPhone 14"
      fail-fast: false
    runs-on: macos-14
    defaults:
      run:
        working-directory: ./packages/home_widget/example
    steps:
      - uses: actions/checkout@v2
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
      - uses: subosito/flutter-action@v1
        with:
          channel: beta
      - uses: bluefireteam/melos-action@v3
      - uses: futureware-tech/simulator-action@v1
        id: simulator
        with:
          model: ${{ matrix.device }}
      - name: "Run iOS integration tests"
        run: flutter test integration_test/ios_test.dart -d ${{steps.simulator.outputs.udid}}