name: Check Pull Requests

on:
  pull_request:

jobs:
  quality:
    name: Quality Checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1.4.0
        with:
          channel: stable
      - name: Get Packages
        run: flutter pub get
      - name: Analyze
        run: flutter analyze
      - name: Format
        run: flutter format . --set-exit-if-changed
      - name: Test
        run: flutter test --coverage
      - uses: VeryGoodOpenSource/very_good_coverage@v1.1.1

  android:
    name: Android Integration Tests
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.4.0
        with:
          channel: stable
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck