name: generator_basics
description: "A minimal example showcasing the home_widget_generator and home_widget_cli packages."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  home_widget:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  home_widget_cli:
  home_widget_generator:

flutter:
  uses-material-design: true
